### PR TITLE
capstone: Fix Linux install

### PR DESCRIPTION
**Pull request by dholm**

### CODE REVIEW

**Comment by dholm** [comment]
I was told to resubmit here?
https://github.com/Homebrew/homebrew/pull/49779

**Comment by sjackman** [comment]
For future contributions the preferred commit message is `capstone: Fix for Linuxbrew`

**Comment by sjackman** [comment]
Merged as
```ruby
    system "./make.sh"
    if OS.mac?
      system "./make.sh", "install"
    else
      system "make", "install", "PREFIX=#{prefix}"
    end
```

**Comment by sjackman** [comment]
Thanks again for your contribution, David!

**Pull request closed without merging**
