### PR TITLE
Fish: depends on ncurses

### LINKED ISSUE #1079: Fish depends on ncurses
This is not an issue (yet) but a question. When I installed `fish` I needed to run `sudo yum install -y ncurses-devel` or the build would fail. I remember having to do this for another package (can't remember the exact one) as well. Is this by design or should the formula include these in their dependencies?

### PR DESCRIPTION
**Pull request by andrewrynhard**

### CODE REVIEW

**Comment by sjackman** [comment]
`brew test fish` fails. See https://travis-ci.org/Linuxbrew/linuxbrew/builds/124236894#L652
Can you reproduce this failure?

```
==> brew test --verbose fish
Testing fish
==> /home/travis/build/Linuxbrew/linuxbrew/Cellar/fish/2.2.0/bin/fish -c echo
.
Last 150 lines from /home/travis/.cache/Homebrew/Logs/fish/01.fish:
2016-04-19 16:33:58 +0000
/home/travis/build/Linuxbrew/linuxbrew/Cellar/fish/2.2.0/bin/fish
-c
echo
/home/travis/build/Linuxbrew/linuxbrew/Cellar/fish/2.2.0/bin/fish: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
Error: fish: failed
```

**Comment by sjackman** [comment]
I'm currently splitting `Linuxbrew/linuxbrew` into `Linuxbrew/brew` and `Linuxbrew/homebrew-core`, as Homebrew did last week (two weeks ago?), so I'm not merging any pull requests right now. I'll cherry-pick this PR after the split is complete, probably next week. Sorry for the delay.

**Comment by andrewrynhard** [comment]
I get 

````
 brew test --verbose fish
Error: cannot load such file -- minitest/unit
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/ruby/test/unit/assertions.rb:1:in `<top (required)>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/vagrant/.linuxbrew/Library/Homebrew/formula_assertions.rb:7:in `rescue in <module:Assertions>'
/home/vagrant/.linuxbrew/Library/Homebrew/formula_assertions.rb:4:in `<module:Assertions>'
/home/vagrant/.linuxbrew/Library/Homebrew/formula_assertions.rb:2:in `<module:Homebrew>'
/home/vagrant/.linuxbrew/Library/Homebrew/formula_assertions.rb:1:in `<top (required)>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/vagrant/.linuxbrew/Library/Homebrew/cmd/test.rb:2:in `<top (required)>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/vagrant/.linuxbrew/Library/brew.rb:21:in `require?'
/home/vagrant/.linuxbrew/Library/brew.rb:56:in `<main>'
````

**Comment by sjackman** [comment]
I believe that error is caused by using `ruby` 1.9.3. `brew install ruby` should fix it.

**Comment by sjackman** [comment]
This PR built correctly on the LinuxbrewTestBot.

**Comment by rwhogg** [comment]
@andrewrynhard, now that the merge is complete, mind reopening this PR against the linuxbrew/homebrew-core repository? Thanks a bunch!

Closing for now.

**Pull request closed without merging**
