### PR TITLE
cairo: depends on recommended x11 for Linuxbrew

### PR DESCRIPTION
**Pull request by DoomHammer**
As in #974

### CODE REVIEW

**Comment by DoomHammer** [comment]
It seems `:recommended` dep on `:x11` changes exactly nothing therefore Travis doesn't install X11 deps. Any ideas how to overcome this?

**Comment by sjackman** [comment]
[requirements/x11_requirement.rb](https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Homebrew/requirements/x11_requirement.rb) and possibly [os/mac/xquartz.rb](https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Homebrew/os/mac/xquartz.rb) need to be modified to pull in `linuxbrew/xorg/xorg` by default. @rwhogg @maxim-belkin

**Comment by maleghast** [comment]
Is there any chance that someone can merge this..?  I really want to install Elixir on my new work Linux machine, and I would MUCH rather do it with Brew than from scratch, but I can't at the moment because of this bug in the Cairo build, Cairo being a dep for Elixir.

**Comment by DoomHammer** [comment]
I believe it depends on #1039 right now.

Also, if you want `cairo` you can `brew install linuxbrew/xorg/xorg && brew install cairo`. I think this should help you.

**Comment by sjackman** [comment]
As Piotr mentioned, but also add `--with-x11` to `cairo`.
```sh
brew install linuxbrew/xorg/xorg && brew install cairo --with-x11
```

**Comment by sjackman** [comment]
I'm happy with merging this patch as is.

**Comment by maleghast** [comment]
Thanks guys :-)  I am still getting the hang of making stuff work on Linux - been on a Mac for work for 14 years...  I ran into another issue to do with wxmac, but thanks for getting me this far.

**Comment by sjackman** [comment]
Thanks, Piotr!

**Comment by 7kemZmani** [comment]
`As Piotr mentioned, but also add --with-x11 to cairo.

brew install linuxbrew/xorg/xorg
brew install cairo --with-x11
brew install elixir`

doesn't work :-1:  I'm getting:
Warning: cairo: this formula has no --with-x11 option so it will be ignored!

**Comment by rwhogg** [comment]
I modified `cairo` recently; can you try

```
brew update
brew install cairo
```

If that fails, you can try `brew install cairo --env=std`.

**Comment by maxim-belkin** [comment]
the log clearly says 
```
checking for xcb... no
```
After doing what @rwhogg suggested, try `brew install libxcb`

**Comment by 7kemZmani** [comment]
@rwhogg 

> If that fails, you can try brew install cairo --env=std.

This line did it for me, 
Thanks!

**Comment by 7kemZmani** [comment]
@maxim-belkin 

> brew install libxcb
Warning: linuxbrew/xorg/libxcb-1.12 already installed

**Comment by maxim-belkin** [comment]
my solution was a back up solution in case @rwhogg's didn't work. 
So, which line exactly worked for you

**Comment by maxim-belkin** [comment]
Weird... I'd suggest you run the following code:
```sh
dir="$(pwd)"
cd "$(brew --repo)"
git checkout master
git reset --hard origin/master
git fetch --unshallow
git pull origin master
for tap in $(brew tap); do
    cd "$(brew --repo $tap)"
    git checkout master
    git reset --hard origin/master
    git fetch --unshallow
    git pull origin master
done
cd "$dir"
unset dir
```

**Comment by 7kemZmani** [comment]
result:
`Switched to branch 'master'
HEAD is now at dc9752e Add symlink_host_gcc: Symlink the host's compiler for Linuxbrew (#358)
remote: Counting objects: 329, done.
remote: Compressing objects: 100% (153/153), done.
remote: Total 329 (delta 191), reused 297 (delta 160), pack-reused 0
Receiving objects: 100% (329/329), 148.56 KiB | 0 bytes/s, done.
Resolving deltas: 100% (191/191), completed with 17 local objects.
From https://github.com/Linuxbrew/brew
 * [new branch]      gh-pages   -> origin/gh-pages
From https://github.com/Linuxbrew/brew
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
HEAD is now at 49aca39 CONTRIBUTING.md: Fix typos (#12)
remote: Counting objects: 97, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 97 (delta 59), reused 88 (delta 50), pack-reused 0
Unpacking objects: 100% (97/97), done.
From https://github.com/Linuxbrew/homebrew-extra
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
HEAD is now at 576e451 xorg-protocols: fix dependencies and URL
remote: Counting objects: 2426, done.
remote: Compressing objects: 100% (607/607), done.
remote: Total 2426 (delta 1886), reused 2359 (delta 1819), pack-reused 0
Receiving objects: 100% (2426/2426), 408.08 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1886/1886), completed with 64 local objects.
From https://github.com/Linuxbrew/homebrew-xorg
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
HEAD is now at ef5061d travis: reconcile with homebrew/science (#2560)
remote: Counting objects: 356177, done.
remote: Compressing objects: 100% (146355/146355), done.
remote: Total 356177 (delta 210878), reused 352305 (delta 207018), pack-reused 0
Receiving objects: 100% (356177/356177), 121.33 MiB | 3.39 MiB/s, done.
Resolving deltas: 100% (210878/210878), completed with 3678 local objects.
From https://github.com/Linuxbrew/homebrew-core
 * branch            master     -> FETCH_HEAD
Already up-to-date.`

**Comment by maxim-belkin** [comment]
LGTM. Now you can try
```
brew remove cairo
brew install cairo
brew gist-logs cairo
```
and report here the url you get in the end

**Comment by 7kemZmani** [comment]
I'm getting an error when I try:
> brew remove cairo
..
because it is required by harfbuzz 1.4.6, atk 2.24.0, gdk-pixbuf 2.36.6, gobject-introspection 1.52.0_1, which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies cairo

no I'm afraid that 'brew uninstall --ignore-dependencies cairo' is going to break something else :/
so, are things going to go back to normal after forcing the removal of the dependencies, and reinstalling cairo?

**Comment by maxim-belkin** [comment]
You will be able to repeat `brew install --env=std cairo` after you do the above steps. I just want to figure out what prevents you from installing `cairo` in super env.

**Comment by 7kemZmani** [comment]
@maxim-belkin 
https://gist.github.com/308f50a16f3631424cd57932aea01771

**Comment by maxim-belkin** [comment]
So.... now you were able to install `cairo` in superenv, is that right?

**Comment by maxim-belkin** [comment]
superenv -- this is the default env. in Linuxbrew when you don't specify `--env=std`.

**Comment by 7kemZmani** [comment]
good...
now that we got 'cairo' to install properly, I'm getting the same problem with 'gtk+' this time.
these are all for the sake of:
`brew install erlang`

(heading back to google)

**Comment by maxim-belkin** [comment]
You can report that in [Linuxbrew/homebrew-core](https://github.com/Linuxbrew/homebrew-core/issues), not here. This is a legacy repo... :)

**Comment by maxim-belkin** [comment]
Can you create an issue there and post the result you get after executing the following commands:
```
brew install -vds gtk+
brew gist-logs gtk+
```

**Comment by 7kemZmani** [comment]
[#2564](https://github.com/Linuxbrew/homebrew-core/issues/2564)

**Pull request closed without merging**
