### PR TITLE
glibc: depends on gawk

### PR DESCRIPTION
**Pull request by DoomHammer**
Details: #953

### CODE REVIEW

**Comment by sjackman** [comment]
`xz` was installed by bottle, but that bottle is not working on the Travis CI system.
https://travis-ci.org/Linuxbrew/linuxbrew/builds/117300152#L655-L658
```
==> Downloading http://ftpmirror.gnu.org/gawk/gawk-4.1.3.tar.xz
Already downloaded: /home/travis/.cache/Homebrew/gawk-4.1.3.tar.xz
==> Verifying gawk-4.1.3.tar.xz checksum
Error: Empty archive
```

**Comment by sjackman** [comment]
Travis CI is running Ubuntu 12 Trusty.
It compiled successfully on LinuxbrewTestBot running Ubuntu 14 Precise.
See https://github.com/LinuxbrewTestBot/linuxbrew/tree/pr-DoomHammer-add-glibc-deps

**Comment by sjackman** [comment]
See #968 xz: Error: Empty archive

**Comment by DoomHammer** [comment]
Yet another reason to give #601 a try? ;)

**Comment by sjackman** [comment]
I fixed #968 xz: Error: Empty archive

**Comment by sjackman** [comment]
I would like any deps of the toolchain (i.e. `glibc` and `gcc`) to be bottled, to make installing the toolchain quick and painless. `gawk` doesn't say it's `cellar :any`, but I suspect it would work just fine.

Anything bottles installed before `glibc` (that is any deps of `glibc`, like `zlib` and `binutils`) have to be built on a "holy build box" with glibc 2.5, the oldest glibc supported to bootstrap Linuxbrew. The downside to that solution is that these "compatible" bottles have to be built by hand. So I want to avoid adding hard deps to `glibc`, and most systems do provide `gawk`.

I suggest adding a `Requirement` rather than a dependency that first checks whether the system provides `awk`, and if not builds `gawk` from source. `gawk` takes one minute to build, so perhaps I'm overthinking this, but it's a simple fix.

```ruby
class AwkRequirement < Requirement
  fatal true
  default_formula "gawk"
  satisfy { which "awk" }
end
```

**Comment by DoomHammer** [comment]
Understood, sir!

BTW: why build by hand on a holy machine? Can't we make a holy Docker container just for that?

**Comment by sjackman** [comment]
For sure! Any distribution that uses `glibc` 2.5 will do just fine. CentOS 5 for example, though I'd prefer a Debian or Ubuntu release that also used `glibc` 2.5.

**Comment by DoomHammer** [comment]
BTW: where does `linuxbrew/linuxbrew` come from as it is not the `Dockerfile` from current repo for sure?

**Comment by DoomHammer** [comment]
OK, nevermind that. I pushed `doomhammer/linuxbrew-lenny` to Docker cloud but wouldn't call it working.

When I issued `brew install gcc --with-glibc --verbose` it got stuck:

```
==> Installing dependencies for gcc: patchelf, zlib, binutils, linux-headers, glibc, xz, gmp, gpatch, mpfr, libmpc, isl
==> Installing gcc dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.9.x86_64_linux.bottle.tar.gz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.1.5-273; x86_64-linux) https://linuxbrew.bintray.com/bottles/patchelf-0.9.x86_64_linux.bottle.tar.gz -C 0 -o /home/linuxbrew/.cache/Home
brew/patchelf-0.9.x86_64_linux.bottle.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  285k  100  285k    0     0   129k      0  0:00:02  0:00:02 --:--:--  140k
==> Verifying patchelf-0.9.x86_64_linux.bottle.tar.gz checksum
==> Pouring patchelf-0.9.x86_64_linux.bottle.tar.gz
tar xvf /home/linuxbrew/.cache/Homebrew/patchelf-0.9.x86_64_linux.bottle.tar.gz
tar: Failed to set default locale
x patchelf/0.9/
x patchelf/0.9/bin/
x patchelf/0.9/bin/patchelf
x patchelf/0.9/share/
x patchelf/0.9/share/doc/
x patchelf/0.9/share/doc/patchelf/
x patchelf/0.9/share/doc/patchelf/README
x patchelf/0.9/share/man/
x patchelf/0.9/share/man/man1/
x patchelf/0.9/share/man/man1/patchelf.1
x patchelf/0.9/COPYING
x patchelf/0.9/INSTALL_RECEIPT.json
x patchelf/0.9/README
```

Funny thing, running `brew install patchelf` seemed to work, but then:

```
==> Installing dependencies for gcc: zlib, binutils, linux-headers, glibc, xz, gmp, gpatch, mpfr, libmpc, isl
==> Installing gcc dependency: zlib
==> Downloading https://linuxbrew.bintray.com/bottles/zlib-1.2.8.x86_64_linux.bottle.1.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/zlib-1.2.8.x86_64_linux.bottle.1.tar.gz
==> Verifying zlib-1.2.8.x86_64_linux.bottle.1.tar.gz checksum
==> Pouring zlib-1.2.8.x86_64_linux.bottle.1.tar.gz
tar xvf /home/linuxbrew/.cache/Homebrew/zlib-1.2.8.x86_64_linux.bottle.1.tar.gz
tar: Failed to set default locale
x zlib/1.2.8/
x zlib/1.2.8/ChangeLog
x zlib/1.2.8/lib/
x zlib/1.2.8/lib/libz.so.1
x zlib/1.2.8/lib/libz.so.1.2.8
x zlib/1.2.8/lib/pkgconfig/
x zlib/1.2.8/lib/pkgconfig/zlib.pc
x zlib/1.2.8/lib/libz.a
x zlib/1.2.8/lib/libz.so
x zlib/1.2.8/README
x zlib/1.2.8/INSTALL_RECEIPT.json
x zlib/1.2.8/include/
x zlib/1.2.8/include/zlib.h
x zlib/1.2.8/include/zconf.h
x zlib/1.2.8/share/
x zlib/1.2.8/share/man/
x zlib/1.2.8/share/man/man3/
x zlib/1.2.8/share/man/man3/zlib.3
/home/linuxbrew/.linuxbrew/Cellar/patchelf/0.9/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.8/lib/libz.so.1.2.8
```

Could you point me @sjackman where to go from here as I am still not very familiar with Homebrew internals?

Thanks!

**Comment by sjackman** [comment]
`tar: Failed to set default locale`
See https://github.com/Linuxbrew/linuxbrew/blob/master/Dockerfile#L9

**Comment by sjackman** [comment]
Is it just hanging after extracting the tarball? I've seen that behaviour too on Ubuntu 12 precise, and haven't figured it out.

**Comment by sjackman** [comment]
For my own reference:
History of Debian releases: https://wiki.debian.org/DebianReleases
History of glibc releases: https://sourceware.org/glibc/wiki/Glibc%20Timeline

**Comment by DoomHammer** [comment]
`localedef` on lenny have no notion of `-i` switch. That is why I omitted
this.

As for hanging: this is what it looks like. May try a bit of `strace`ing
but other than that, no idea.

**Comment by sjackman** [comment]
Lenny probably didn't support UTF-8 either.

I noticed that Ruby was still using CPU, so I think it was stuck in some kind of loop. Possibly (long shot here) due to a missing program.

**Comment by DoomHammer** [comment]
I'd also bet for a missing program. Maybe `command-not-found`'s approach would help here?

**Comment by DoomHammer** [comment]
Funny thing. Should `cc1` be running during pouring bottle? I thought this process was more like: "unpack your things and move them to correct places"...

**Comment by sjackman** [comment]
No, `cc1` should not be running when pouring a bottle. `pstree` may be useful to see who's running it.

**Comment by DoomHammer** [comment]
While running `brew install binutils --verbose`:

```
$ pstree
bash-+-pstree
     `-ruby-+-ruby-+-ruby-+-make---sh---make---sh---sh---make---make---sh---make---8*[gcc-4.3-+-as]
            |      |      |                                                                   `-cc1]
            |      |      `-{ruby}
            |      `-{ruby}
            `-{ruby}
```

The output on the other hand was:

```
[...]
/home/linuxbrew/.linuxbrew/Cellar/patchelf/0.9/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/binutils/2.25.1/x86
_64-unknown-linux-gnu/bin/objdump 
/home/linuxbrew/.linuxbrew/Cellar/patchelf/0.9/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/binutils/2.25.1/x86
_64-unknown-linux-gnu/bin/ranlib 
/home/linuxbrew/.linuxbrew/Cellar/patchelf/0.9/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so /home/linuxbrew/.linuxbrew/Cellar/binutils/2.25.1/x86
_64-unknown-linux-gnu/bin/strip
```

**Comment by DoomHammer** [comment]
Come to think of it, maybe 4.3 was deprecated based on fact it has some weird loop issue or some such?

Still: what is that guy even doing when I am pouring from a bottle?

**Comment by sjackman** [comment]
It's clearly compiling something. It looks as though the output is not updated, but brew has moved on to compiling a formula. Does `ps aux |egrep 'make|sh'` give some indication of what's being compiled? You can also poke around in `/proc` to figure out what these processes are up to.

**Comment by DoomHammer** [comment]
What is being compiled is usually what is being installed. I am more concerned whether it is done after pouring. Is there some logic in place to build from source after pouring is done (eg. if poured bottled is incompatible with the system or something like that)?

**Comment by DoomHammer** [comment]
Another interesting question: what could be blocking output? I clearly see in `ps aux` that installation of `binutils` is taking place whereas console seems stuck on:

```
brew install binutils
==> Installing dependencies for binutils: patchelf, zlib
==> Installing binutils dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.9.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring patchelf-0.9.x86_64_linux.bottle.tar.gz
```

**Comment by DoomHammer** [comment]
In the meanwhile `zlib` got silently installed as well.

**Comment by sjackman** [comment]
It looks like the console has hang up. Perhaps its file descriptor was inadvertently closed.

**Comment by DoomHammer** [comment]
Tried my luck with Centos and things were mostly smooth, until `gawk` couldn't link. Maybe this is a dead end, in fact?

As a workaround one might create a fake keg with `curl -Lq s.minos.io/s > /home/linuxbrew/static-get &&         sh /home/linuxbrew/static-get -x gawk`...

**Comment by sjackman** [comment]
That's the first that I've heard of `minos`. It's not a bad workaround, but I'd prefer to install `gawk` using Linuxbrew.

**Comment by DoomHammer** [comment]
I would too, but no luck on ancient distro ;)

**Comment by sjackman** [comment]
Where are you stuck? With the broken console? I haven't figured that one out yet myself.
I regularly use Linuxbrew on CentOS 5.11 with glibc 2.5.

**Comment by DoomHammer** [comment]
Console problems were on Debian Lenny. `gawk` on CentOS couldn't build due to some reloc problem, which I suspect means linker is too old.

**Comment by sjackman** [comment]
Can you post the error message?

**Comment by DoomHammer** [comment]
My bad, linking error was with something different altogether. `gawk` was pretty simple:

```
==> Installing dependencies for gawk: xz
==> Installing gawk dependency: xz
==> Downloading https://linuxbrew.bintray.com/bottles/xz-5.2.2.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring xz-5.2.2.x86_64_linux.bottle.tar.gz
/home/linuxbrew/.linuxbrew/Cellar/xz/5.2.2: 65 files, 1.6M
==> Installing gawk
==> Downloading http://ftpmirror.gnu.org/gawk/gawk-4.1.3.tar.xz
==> Downloading from http://ftp.task.gda.pl/pub/gnu/gawk/gawk-4.1.3.tar.xz
######################################################################## 100.0%
Error: Empty archive
```

This is both well-known and a circular dependency (I cannot install `glibc` if we want `gawk` linked against the old `glibc`). Workaround might perhaps be to install non-brewed `xz`?

**Comment by sjackman** [comment]
Ah, `xz` is linked against new `glibc`. As a temporary workaround, use the `gz` `http://ftpmirror.gnu.org/gawk/gawk-4.1.3.tar.gz` rather than `xz`.

**Comment by sjackman** [comment]
As discussed, this fix requires an `:awk` requirement, so as to avoid adding a build dependency to `binutils`. Closing this PR for now, before the grand split of `brew` and `homebrew-core`.

**Pull request closed without merging**
