### PR TITLE
duck 4.8.18316

### PR DESCRIPTION
**Pull request by G-Square**
# Contributing to Linuxbrew:

To contribute a new formula or a new version of an existing formula, please submit your pull request to [Homebrew](https://github.com/Homebrew/homebrew) rather than to Linuxbrew. Patches to fix issues that you have reproduced on both Linuxbrew and Homebrew should be sent to Homebrew. Please send your pull request to Linuxbrew if you are in doubt.

Patches to fix issues particular to Linux should not affect the behaviour of the formula on Mac. Use `if OS.mac?` and `if OS.linux?` as necessary to preserve the existing behaviour on Mac. For example, to add a new dependency that is not necessary on Mac:

```ruby
depends_on "zlib" unless OS.mac?
```

### All Submissions:

_You can erase any parts of this template not applicable to your Pull Request._

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/linuxbrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/linuxbrew/pulls) for the same update/change?
- [ ] Have you included a log of the failed build without your patch using `brew gist-logs <formula>`?
- [ ] Does your submission pass
`brew audit --strict <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>`?

### Changes to Linuxbrew's Core:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031) if you'd like one.
- [ ] Have you successfully ran `brew tests` with your changes locally?

### CODE REVIEW

**Comment by G-Square** [comment]
Need Java 1.8 on CI 
Thanks

**Comment by rwhogg** [comment]
Hey @G-Square, can you send this pull request upstream to Homebrew please?

Also:

* Is XCode not required on OS X any more, or is that a Linux-specific change? If it's a Linux specific change, then use `if OS.mac?` if necessary rather than removing it (and submit a separate PR here rather than including that change upstream, as they won't want it). If it's not necessary for the formula to build on Linux, please don't remove that line. If XCode isn't required any more on OS X, than feel free to send that change upstream to Homebrew as well.
* Can you explain why you changed the Java version from "1.8+" to "1.8"?

Thanks!

**Comment by G-Square** [comment]
I will create a new PR with `if OS.mac?` and `1.8+`.
I changed Java version due to Travis constant use of  `1.7`, line 91-92:`Java version: 1.7.0_80, vendor: Oracle Corporation`.
Although it seemed highly unlike, I checked to see if extra `+` was the cause.
Is `Java 1.8.*` installed but not triggered on Travis?

Thanks

**Comment by rwhogg** [comment]
The Java version constraint actually has no effect on Linux. We would have to modify .travis.yml to get Java 8 to install on Travis.

**Comment by G-Square** [comment]
It kinda getting annoying as both `homebrew-core` and now renamed `legacy-homebrew` on Jenkins both have errors parsing XML UTF-8 on this update. And now Travis also has issues. 
Honestly for a simple update, I thought this process would be seamless.
Let me know it something changes.

Thanks!

**Comment by sjackman** [comment]
Linuxbrew has transitioned through the separation of `brew` and `core` yet. It'll probably happen next week.

What are the "errors parsing XML UTF-8" that you mention? Is it related to this issue, or a more general issue?

Are you having any trouble building `duck`, or are you just updating the version? If you are encountering an error message, please report `brew gist-logs ducks`. If the latter, please send the updated version upstream to `Homebrew/homebrew`, as Bob mentioned.

I'm going to close this issue. Feel free to reopen if you are encountering an error building `duck` on Linux.

**Comment by apjanke** [comment]
> What are the "errors parsing XML UTF-8" that you mention? Is it related to this issue, or a more general issue?

This is more of a `brew test-bot` bug.

This happens on the test bot if the build or test script emits certain UTF-8 characters that aren't allowed in XML, or bytes that aren't valid UTF-8 text. The Jenkins test results are output in an XML file, and if it's invalid, the test run fails. `brew test-bot` tries to filter them out and ensure valid output, but it's not fully correct yet. There's no open issue for it; Homebrew/legacy-homebrew#50092 was an attempt to fix this. We'll get it soon.

**Comment by sjackman** [comment]
Thanks for the update, Andrew.

**Pull request closed without merging**
