### PR TITLE
rust: Fix Rust 1.6.0 build

### PR DESCRIPTION
**Pull request by palad1**
Fix bootstraping of Cargo by using a newer snapshot of Cargo compatible with the current version of crates.io

### CODE REVIEW

**Comment by sjackman** [comment]
What error message without this patch are you trying to fix? Please report `brew gist-logs rust`.

Can you test on Mac, and does this issue also affect Mac OS? If so, please send this patch upstream to Homebrew/homebrew.

**Comment by rwhogg** [comment]
Looks potentially related to #412.

**Comment by rwhogg** [comment]
@palad1 new versions of Rust/Cargo were committed [here](https://github.com/Linuxbrew/linuxbrew/commit/f939575005011d0681227aa530552d264edd933a#diff-5228b5cf14fdcdd1f7e2c1fd8091ad86).

Does the problem still occur for you?

**Comment by sjackman** [comment]
I believe the `cargo` resource has been bumped to `0.9.0` by upstream Homebrew and merged into Linuxbrew, resolving this issue.

**Pull request closed without merging**
