### PR TITLE
mediaconch: fix libxslt dependency

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by sjackman** [comment]
Hi, Reto. For future contributions, please post the exact error message (ideally with a gist) that you're observing without the patch applied.

**Comment by sjackman** [comment]
```
configure: error: libxml2 configuration is not found
```

**Comment by retokromer** [comment]
I will. Thank you for the hint!

**Comment by sjackman** [comment]
The preferred commit message is
`mediaconch: Depends on libxslt for Linuxbrew`

Merged! Thanks for your contribution, Reto.

**Pull request closed without merging**
