### PR TITLE
rtags: fix for linuxbrew

### LINKED ISSUE #1018: rtags: cannot find -lc++abi
```
/home/linuxbrew/.linuxbrew/Cellar/cmake/3.5.1/bin/cmake -E
cmake_link_script CMakeFiles/cmTC_dea4d.dir/link.txt --verbose=1
/usr/bin/gcc-4.8 -Os -w -pipe -march=core2 -L/home/linuxbrew/.linuxbrew/lib
-Wl,--dynamic-linker=/home/linuxbrew/.linuxbrew/lib/ld.so
-Wl,-rpath,/home/linuxbrew/.linuxbrew/lib -lc++abi
CMakeFiles/cmTC_dea4d.dir/testCCompiler.c.o -o cmTC_dea4d -rdynamic
/usr/bin/ld: cannot find -lc++abi
collect2: error: ld returned 1 exit status
make[1]: *** [cmTC_dea4d] Error 1
make[1]: Leaving directory
`/tmp/rtags20160330-4942-18ao3ix/build/CMakeFiles/CMakeTmp'
```

### PR DESCRIPTION
**Pull request by DoomHammer**
Fixes #1018

### CODE REVIEW

**Comment by sjackman** [comment]
BrewTestBot gave this error:
```
brew update
curl: symbol lookup error: /home/linuxbrew/.linuxbrew/lib/libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos
```
I haven't seen this error before.

**Comment by sjackman** [comment]
Oh, I see why. A few lines before it uninstalls `openssl`.
```
==> brew uninstall --force homebrew/dupes/libedit llvm openssl python zlib
```

**Comment by DoomHammer** [comment]
Why does it do so?

**Comment by sjackman** [comment]
`test-bot`:
+ installs the formula's dependencies
+ installs the formula
+ removes the build deps of the formula
+ tests the formula
+ removes the formula
+ removes the deps of the formula
+ installs the newly built bottle of the formula along with its deps
+ tests the formula
+ removes the formula
+ removes the deps of the formula

```
==> brew install --only-dependencies --verbose --build-bottle rtags
==> brew install --verbose --build-bottle rtags
==> brew audit rtags
==> brew bottle --verbose --rb rtags --keep-old
==> brew bottle --merge --write --no-commit ./rtags-2.2.x86_64_linux.bottle.rb --keep-old
==> brew uninstall --force rtags
==> brew uninstall --force bzip2 cmake curl git gpatch makedepend pkg-config sphinx-doc xz
==> brew install ./rtags-2.2.x86_64_linux.bottle.tar.gz
==> brew test --verbose rtags
==> brew uninstall --force rtags
==> brew uninstall --force homebrew/dupes/libedit llvm openssl python zlib
```

**Comment by sjackman** [comment]
My proposed solution is to have a list of essential build deps that are never removed.
Another solution would be to use `brew missing` to remove broken packages with missing deps.

**Comment by sjackman** [comment]
What I don't understand is why `curl` is still installed but `openssl` has been removed.

**Comment by sjackman** [comment]
Here's my list of essential dependencies of `curl`, `git` and `gcc`:
```ruby
["zlib", "openssl", "glibc", "gmp", "mpfr", "libmpc", "isl", "curl", "expat"]
```

**Comment by sjackman** [comment]
My attempt at a fix for the test-bot removing essential dependencies is in #1024.

**Comment by DoomHammer** [comment]
Any plans on merging that one?

**Comment by sjackman** [comment]
Go ahead and merge this PR if you like, ignoring the test failure.

**Comment by sjackman** [comment]
Please merge this patch. It's good to go! #1024 can wait for another day.

**Comment by sjackman** [comment]
Thanks, Piotr!

**Pull request closed without merging**
