### PR TITLE
gtk+: depends on cairo --with-x11 for Linuxbrew

### PR DESCRIPTION
**Pull request by DoomHammer**
As reported in #632

### CODE REVIEW

**Comment by sjackman** [comment]
:+1+

**Comment by sjackman** [comment]
Merged. Thanks, Piotr!

**Comment by sjackman** [comment]
On second thought, this issue should have been resolved differently.
`:x11` should be a `:recommended` dependency of `cairo` for non-Mac systems.
Would you like to take a stab at a patch that does that, then I'll revert this patch.

**Comment by DoomHammer** [comment]
Not sure if I am capable but will give this a try tomorrow (so probably late evening for you, @sjackman ;) ).

**Comment by sjackman** [comment]
See for example https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Formula/htop.rb#L18

**Comment by DoomHammer** [comment]
Something like #986?

**Comment by sjackman** [comment]
Yep, that looks about right to me. Thanks, Piotr.

**Pull request closed without merging**
