### PR TITLE
core: Fix march for linux

### PR DESCRIPTION
**Pull request by alekseysidorov**
### Changes to Linuxbrew's Core:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031) if you'd like one.
- [ ] Have you successfully ran `brew tests` with your changes locally?

### CODE REVIEW

**Comment by sjackman** [comment]
Fixes Linuxbrew/linuxbrew#1053

**Comment by sjackman** [comment]
I'm currently splitting `Linuxbrew/linuxbrew` into `Linuxbrew/brew` and `Linuxbrew/homebrew-core`, as Homebrew did last week (two weeks ago?), so I'm not merging any pull requests right now. I'll cherry-pick this PR after the split is complete, probably next week. Sorry for the delay.

**Comment by sjackman** [comment]
👍 Look's great! Thanks, Aleksey.

**Comment by eiennohito** [comment]
What should I do if I have a grid of machines with different CPU and want to specify a the oldest march, native won't work for me.

**Comment by sjackman** [comment]
If you specify `--build-bottle` it will target `-march=core2`. Will that work for you?

**Comment by eiennohito** [comment]
The ability to override target architecture using an environment variable would be better and less error prone. I definitely will forget about bottles myself some time in future and I would need to teach other people to use that.

**Comment by sjackman** [comment]
`brew install --build-bottle foo` installs a formula as normal but sets `-march=core2` and disables postinstall. There's also the `--bottle-arch` option, but the value has to be from one of the values found in
https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Homebrew/os/linux/hardware.rb#L3-L5

**Comment by eiennohito** [comment]
Is it possible to make Homebrew prefer value of `-march` in `CFLAGS`/`CXXFLAGS` to guessed ones?

**Comment by sjackman** [comment]
No, `CFLAGS` and `CXXFLAGS` and other environment variables are intentionally removed from the environment before building for reproducibility. What architecture are you targeting? i.e. what value of `-march` do you want to use?

**Comment by eiennohito** [comment]
We have Xeons from Nehalem and up. So core2.

By the way, will the --build-bottle flag work with upgrade command?

**Comment by sjackman** [comment]
A `HOMEBREW_ARCH` environment variable may be a better fit for your use case. Can you please open an feature request issue to discuss?

**Comment by eiennohito** [comment]
Okay. Should I do it in this repo?

**Comment by sjackman** [comment]
Yes, please.

**Comment by alekseysidorov** [comment]
When you are going to cherry-pick this fix?

**Comment by sjackman** [comment]
Sorry for the delay, and thanks for the bump, Aleksey. I'll do it today.

**Comment by sjackman** [comment]
Moved to https://github.com/Linuxbrew/brew/pull/21

**Pull request closed without merging**
