### PR TITLE
curl: Depends on openldap for Linuxbrew

### PR DESCRIPTION
**Pull request by zbeekman**
Tested with hashicorp/precise64 image

### CODE REVIEW

**Comment by sjackman** [comment]
Please change this to
```ruby
depends_on "Homebrew/dupes/openldap" => :optional
```
Please remove
```ruby
  option "without-ldap", "Build without LDAP support"
```

**Comment by zbeekman** [comment]
> Please change this to
> 
> depends_on "Homebrew/dupes/openldap" => :optional unless OS.mac?
> Please remove
> 
>   option "without-ldap", "Build without LDAP support"

Good suggestions. I'm still getting used to the succinct power or Ruby.

**Comment by zbeekman** [comment]
Do changes to formulae for Linuxbrew get contributed back upstream, or will they at some point? Just curious because removing the `option "without-ldap"` will remove this option completely from the OS.mac builds.

**Comment by sjackman** [comment]
The option `option "without-ldap"` is in fact specific to the Linuxbrew formula. Typically Linuxbrew patches do not get merged back upstream in Homebrew.

**Comment by sjackman** [comment]
Merged. Thanks for your contribution, Izaak!

**Comment by zbeekman** [comment]
:tada: Thanks again for the awesome project

**Pull request closed without merging**
